const mongoose = require('mongoose');
require('dotenv').config();
const Product = require('./models/Product');

const products = [
  { 
    name: 'Panchakavya Herbal Vastu Agarbathi – Jungle of Woods',
    category: 'Agarbatti',
    catId: 'agarbatti',
    featured: true,
    tagline: 'Rich Earthy Forest Fragrance',
    price: 85,
    originalPrice: 120,
    badge: 'Bestseller',
    rating: 4.9,
    reviews: 214,
    bg: '#f3faf0',
    icon: 'Leaf',
    desc: 'Infused with Panchakavya, neem leaves, bilwa leaves, and a rich earthy forest blend. Charcoal-free, hand-rolled with sacred herbs for Vastu harmony.',
    image: '/images/herbal_agarbathi_category_1777263501880.png',
    details: ['Hand Rolled', 'Panchakavya Blend', 'Charcoal Free', 'Vastu Agarbathi'],
    weight: '100g'
  },
  { 
    name: 'Panchakavya Herbal Vastu Agarbathi – Giggling of Herbs',
    category: 'Agarbatti',
    catId: 'agarbatti',
    tagline: 'Nutmeg, Vettiver & Cardamom Blend',
    price: 85,
    originalPrice: 120,
    badge: 'Popular',
    rating: 4.8,
    reviews: 189,
    bg: '#f0fdf4',
    icon: 'Flower2',
    desc: 'A unique herbal blend of nutmeg, vettiver, cardamom, and clove crafted to promote positivity and balance in your home. Traditional Panchakavya formula.',
    image: '/images/herbal_agarbathi_category_1777263501880.png',
    details: ['Nutmeg & Vettiver', 'Panchakavya Blend', 'Charcoal Free', 'Vastu Agarbathi'],
    weight: '100g'
  },
  { 
    name: 'Panchakavya Herbal Vastu Agarbathi – Little Lavender',
    category: 'Agarbatti',
    catId: 'agarbatti',
    tagline: 'Soothing Lavender Calm',
    price: 85,
    originalPrice: 120,
    badge: 'Calming',
    rating: 4.7,
    reviews: 143,
    bg: '#f5f0fb',
    icon: 'Sparkles',
    desc: 'Calming lavender fragrance with the power of Panchakavya and rare herbs. Perfect for meditation and restful nights.',
    image: '/images/herbal_agarbathi_category_1777263501880.png',
    details: ['Lavender Fragrance', 'Panchakavya Blend', 'Charcoal Free', 'Meditation Grade'],
    weight: '100g'
  },
  { 
    name: 'Panchakavya Herbal Vastu Agarbathi – Absolute Sandal',
    category: 'Agarbatti',
    catId: 'agarbatti',
    featured: true,
    tagline: 'Pure Sandalwood Devotion',
    price: 90,
    originalPrice: 130,
    badge: 'Temple Grade',
    rating: 4.9,
    reviews: 267,
    bg: '#fdf8f0',
    icon: 'Sun',
    desc: 'Premium Sandalwood fragrance blended with authentic Panchakavya for deep, devotional puja sessions. Temple-grade purity.',
    image: '/images/herbal_agarbathi_category_1777263501880.png',
    details: ['Sandalwood Fragrance', 'Panchakavya Blend', 'Temple Grade', 'Charcoal Free'],
    weight: '100g'
  },
  { 
    name: 'Panchakavya Herbal Vastu Agarbathi – Orange Fragrance',
    category: 'Agarbatti',
    catId: 'agarbatti',
    tagline: 'Zesty Citrus & Herbal Uplift',
    price: 85,
    originalPrice: 120,
    badge: 'Refreshing',
    rating: 4.6,
    reviews: 112,
    bg: '#fff9f0',
    icon: 'Citrus',
    desc: 'Bright orange and herbal blend that uplifts the spirit. Made with fresh citrus extracts and sacred Panchakavya. Ideal for daily puja.',
    image: '/images/herbal_agarbathi_category_1777263501880.png',
    details: ['Orange Fragrance', 'Panchakavya Blend', 'Charcoal Free', 'Daily Puja'],
    weight: '100g'
  },
  { 
    name: 'Herbal Mosquito Repellent Incense',
    category: 'Agarbatti',
    catId: 'agarbatti',
    featured: true,
    tagline: 'Natural Protection with Lemongrass & Neem',
    price: 95,
    originalPrice: 140,
    badge: 'Natural Shield',
    rating: 4.7,
    reviews: 198,
    bg: '#f0faf3',
    icon: 'Shield',
    desc: 'Herbal mosquito repellent incense made with lemongrass, neem, and Panchakavya. 100% natural, chemical-free protection for your family.',
    image: '/images/herbal_agarbathi_category_1777263501880.png',
    details: ['Lemongrass & Neem', 'Mosquito Repellent', 'Chemical Free', 'Safe for Families'],
    weight: '100g'
  },
  { 
    name: 'Panchakavya Cup Sambrani',
    category: 'Pooja Essentials',
    catId: 'pooja-essentials',
    featured: true,
    tagline: 'Traditional South Indian Dhoop',
    price: 60,
    originalPrice: 90,
    badge: 'Authentic',
    rating: 4.9,
    reviews: 341,
    bg: '#f4fbf4',
    icon: 'Flame',
    desc: 'Authentic Panchakavya Cup Sambrani made with sacred cow products and natural resins. Purifies the air, removes negative energy, and elevates your puja space.',
    image: '/images/panchakavya_products_category_1777263520616.png',
    details: ['Cup Sambrani', 'Panchakavya Formula', 'Charcoal Free', 'Air Purifying'],
    weight: 'Pack of 10 Cups'
  },
  { 
    name: 'Panchakavya Sambrani Dhoop Powder',
    category: 'Pooja Essentials',
    catId: 'pooja-essentials',
    tagline: 'Traditional Loose Dhoop Powder',
    price: 78,
    originalPrice: 110,
    badge: '29% OFF',
    rating: 4.7,
    reviews: 156,
    bg: '#f7f5f0',
    icon: 'Wind',
    desc: 'Loose Sambrani dhoop powder crafted with Panchakavya, guggul, and loban resins. Burn on charcoal disc or traditional incense holder for a traditional fragrance.',
    image: '/images/panchakavya_products_category_1777263520616.png',
    details: ['Loose Powder', 'Guggul & Loban', 'Panchakavya', 'Traditional Aroma'],
    weight: '100g'
  },
  { 
    name: 'Dhristi Camphor Tablets (25g)',
    category: 'Pooja Essentials',
    catId: 'pooja-essentials',
    subCatId: 'camphor',
    featured: true,
    tagline: 'Pure Camphor for Aarti & Drishti',
    price: 60,
    originalPrice: 80,
    badge: 'Pure',
    rating: 4.8,
    reviews: 289,
    bg: '#ffffff',
    icon: 'Sparkles',
    desc: 'Premium Dhristi camphor tablets for daily Aarti and spiritual rituals. Burns clean with no residue. Ideal for removing negative energy and dosha.',
    image: '/images/camphor_category_1777263590488.png',
    details: ['25g Pack', 'Dhristi Camphor', 'Clean Burn', 'No Residue'],
    weight: '25g'
  },
  { 
    name: 'Dhristi Camphor Tablets (50g)',
    category: 'Pooja Essentials',
    catId: 'pooja-essentials',
    subCatId: 'camphor',
    tagline: 'Pure Camphor for Aarti & Drishti',
    price: 120,
    originalPrice: 160,
    badge: 'Value Pack',
    rating: 4.8,
    reviews: 174,
    bg: '#ffffff',
    icon: 'Sparkles',
    desc: 'Value pack of pure Dhristi camphor tablets. Ideal for temples and daily home use. Burns completely without residue.',
    image: '/images/camphor_category_1777263590488.png',
    details: ['50g Pack', 'Dhristi Camphor', 'Clean Burn', 'Temple Grade'],
    weight: '50g'
  },
  { 
    name: 'Dhristi Camphor Tablets (100g)',
    category: 'Pooja Essentials',
    catId: 'pooja-essentials',
    subCatId: 'camphor',
    tagline: 'Economy Pack – Temple & Home Use',
    price: 200,
    originalPrice: 270,
    badge: 'Economy',
    rating: 4.8,
    reviews: 139,
    bg: '#ffffff',
    icon: 'Sparkles',
    desc: 'Economy pack of premium Dhristi camphor for temples and large households. Consistent quality in every tablet.',
    image: '/images/camphor_category_1777263590488.png',
    details: ['100g Pack', 'Dhristi Camphor', 'Economy Pack', 'Temple & Home'],
    weight: '100g'
  },
  { 
    name: 'Dhristi Camphor Tablets (200g)',
    category: 'Pooja Essentials',
    catId: 'pooja-essentials',
    subCatId: 'camphor',
    tagline: 'Bulk Pack for Temples & Institutions',
    price: 350,
    originalPrice: 480,
    badge: 'Bulk Pack',
    rating: 4.9,
    reviews: 89,
    bg: '#ffffff',
    icon: 'Sparkles',
    desc: 'Large 200g bulk pack of pure Dhristi camphor for temples, institutions, and large families. Best value.',
    image: '/images/camphor_category_1777263590488.png',
    details: ['200g Pack', 'Bulk Value', 'Temple Grade', 'Best Value'],
    weight: '200g'
  },
  { 
    name: 'Sacred 23-Herbal Vibhoothi Powder',
    category: 'Pooja Essentials',
    catId: 'pooja-essentials',
    tagline: 'Holy Ash with 23 Rare Herbs',
    price: 45,
    originalPrice: 65,
    badge: 'Sacred',
    rating: 4.9,
    reviews: 312,
    bg: '#f8f8f8',
    icon: 'Wind',
    desc: 'Sacred Vibhoothi prepared with 23 rare herbs and pure cow dung ash following ancient Siddha traditions. Used for daily abhishekam and blessing.',
    image: '/images/panchakavya_products_category_1777263520616.png',
    details: ['23 Rare Herbs', 'Pure Cow Dung Ash', 'Siddha Tradition', 'Daily Blessing'],
    weight: '50g'
  },
  { 
    name: 'Herbal Kumkum Powder',
    category: 'Pooja Essentials',
    catId: 'pooja-essentials',
    tagline: 'Natural Turmeric-Based Sacred Kumkum',
    price: 30,
    originalPrice: 45,
    badge: 'Natural',
    rating: 4.7,
    reviews: 198,
    bg: '#fff5f5',
    icon: 'Heart',
    desc: 'Naturally prepared herbal Kumkum powder free from chemical dyes. Made with pure turmeric and sacred herbs. Auspicious for all rituals.',
    image: '/images/panchakavya_products_category_1777263520616.png',
    details: ['Chemical Free', 'Turmeric Based', 'Natural Dye', 'Auspicious'],
    weight: '30g'
  },
  { 
    name: 'Herbal Cow Dung Powder',
    category: 'Pooja Essentials',
    catId: 'pooja-essentials',
    tagline: 'Purified & Dried Sacred Powder',
    price: 36,
    originalPrice: 50,
    badge: 'Panchakavya',
    rating: 4.6,
    reviews: 134,
    bg: '#f9fdf9',
    icon: 'Leaf',
    desc: 'Pure herbal cow dung powder processed hygienically for Panchakavya rituals, havan, and Vastu use. Purifies the home environment.',
    image: '/images/panchakavya_products_category_1777263520616.png',
    details: ['Hygienically Processed', 'Panchakavya', 'Vastu Use', 'Havan'],
    weight: '100g'
  },
  { 
    name: 'Divine Herbal Agal Vilaku (Pack of 12)',
    category: 'Pooja Essentials',
    catId: 'pooja-essentials',
    tagline: 'Eco-Friendly Herbal Wicks',
    price: 120,
    originalPrice: 180,
    badge: 'New',
    rating: 4.5,
    reviews: 76,
    bg: '#fdf2f2',
    icon: 'Flame',
    desc: 'Handcrafted herbal wicks (Agal Vilaku) made from cotton and herbal extracts. Release a gentle natural aroma when lit. 12-piece pack.',
    image: '/images/combos_category.png',
    details: ['Pack of 12', 'Herbal Cotton Wick', 'Eco-Friendly', 'Gentle Aroma'],
    weight: 'Pack of 12'
  },
  { 
    name: 'Herbal Orange Face Wash',
    category: 'Personal Care',
    catId: 'personal-care',
    subCatId: 'body-wash',
    featured: true,
    tagline: 'De-Tan & Glow with Vitamin C',
    price: 220,
    originalPrice: 299,
    badge: 'Glow',
    rating: 4.6,
    reviews: 187,
    bg: '#fffbf0',
    icon: 'Sun',
    desc: 'Infused with fresh orange peel extracts and herbal nutrients. Naturally de-tans skin, reduces dark spots and restores a radiant glow. Suitable for all skin types.',
    image: '/images/body_wash_category_1777263606152.png',
    details: ['Orange Peel Extract', 'De-Tanning', 'All Skin Types', 'Herbal Formula'],
    weight: '100ml'
  },
  { 
    name: 'Avocado & Jojoba Herbal Face Wash',
    category: 'Personal Care',
    catId: 'personal-care',
    subCatId: 'body-wash',
    tagline: 'Deep Hydration & Soft Skin',
    price: 220,
    originalPrice: 299,
    badge: 'Hydrating',
    rating: 4.8,
    reviews: 154,
    bg: '#f1f9f1',
    icon: 'Heart',
    desc: 'Enriched with Avocado oils and Jojoba extracts for intense moisture and softness. Gently cleanses without stripping the skin\'s natural oils.',
    image: '/images/body_wash_category_1777263606152.png',
    details: ['Avocado Extract', 'Jojoba Oil', 'Deep Moisturising', 'Gentle Cleanse'],
    weight: '100ml'
  },
  { 
    name: 'Tea Tree Herbal Face Wash',
    category: 'Personal Care',
    catId: 'personal-care',
    subCatId: 'body-wash',
    tagline: 'Acne Control & Oil Balance',
    price: 220,
    originalPrice: 299,
    badge: 'Acne Care',
    rating: 4.7,
    reviews: 211,
    bg: '#f0faf8',
    icon: 'Leaf',
    desc: 'Formulated with pure Tea Tree oil and herbal extracts to control excess oil, fight acne-causing bacteria, and keep your skin clear and refreshed.',
    image: '/images/body_wash_category_1777263606152.png',
    details: ['Tea Tree Oil', 'Acne Control', 'Oil Balancing', 'Antibacterial'],
    weight: '100ml'
  },
  { 
    name: 'Hibiscus Glow Herbal Face Wash',
    category: 'Personal Care',
    catId: 'personal-care',
    subCatId: 'body-wash',
    tagline: 'Natural AHA & Skin Brightening',
    price: 220,
    originalPrice: 299,
    badge: 'Brightening',
    rating: 4.6,
    reviews: 98,
    bg: '#fff0f5',
    icon: 'Flower2',
    desc: 'Hibiscus is nature\'s AHA. This face wash gently exfoliates, brightens dull skin, and promotes an even complexion. Rich in antioxidants.',
    image: '/images/body_wash_category_1777263606152.png',
    details: ['Hibiscus Extract', 'Natural AHA', 'Brightening', 'Antioxidant Rich'],
    weight: '100ml'
  },
  { 
    name: 'Herbal Rose Water (200ml)',
    category: 'Personal Care',
    catId: 'personal-care',
    subCatId: 'rose-water',
    featured: true,
    tagline: 'Pure Distilled Rose Essence',
    price: 30,
    originalPrice: 45,
    badge: 'Pure',
    rating: 4.8,
    reviews: 423,
    bg: '#fff5f8',
    icon: 'Flower2',
    desc: 'Pure steam-distilled rose water. A natural toner, skin refresher, and hair conditioner. Use after face wash or for cooking. 100% chemical free.',
    image: '/images/rose_water_category_1777263539013.png',
    details: ['Steam Distilled', 'No Chemicals', 'Toner & Mist', 'Food Grade'],
    weight: '200ml'
  },
  { 
    name: 'Herbal Rose Water (500ml)',
    category: 'Personal Care',
    catId: 'personal-care',
    subCatId: 'rose-water',
    tagline: 'Pure Distilled Rose Essence',
    price: 60,
    originalPrice: 90,
    badge: 'Value',
    rating: 4.8,
    reviews: 312,
    bg: '#fff5f8',
    icon: 'Flower2',
    desc: 'Economy 500ml bottle of pure steam-distilled rose water. Multi-purpose — use as a skin toner, hair mist, or in cooking. No preservatives added.',
    image: '/images/rose_water_category_1777263539013.png',
    details: ['Steam Distilled', 'No Preservatives', 'Skin & Hair', 'Multi-Purpose'],
    weight: '500ml'
  },
  { 
    name: 'Herbal Rose Water (1 Litre)',
    category: 'Personal Care',
    catId: 'personal-care',
    subCatId: 'rose-water',
    tagline: 'Family-Size Pure Rose Water',
    price: 120,
    originalPrice: 180,
    badge: 'Family Pack',
    rating: 4.9,
    reviews: 198,
    bg: '#fff5f8',
    icon: 'Flower2',
    desc: 'Large 1-litre family pack of pure herbal rose water. Perfect for daily skincare, pooja use, and cooking. Best value for families.',
    image: '/images/rose_water_category_1777263539013.png',
    details: ['1 Litre Pack', 'Steam Distilled', 'Best Value', 'Family Size'],
    weight: '1 Litre'
  },
  { 
    name: 'Pooja Essentials Gift Box',
    category: 'Gifting',
    catId: 'gift-packs',
    featured: true,
    tagline: 'Complete Spiritual Blessing Set',
    price: 499,
    originalPrice: 699,
    badge: 'Gift Set',
    rating: 4.9,
    reviews: 287,
    bg: '#fff5f5',
    icon: 'Gift',
    desc: 'A beautifully curated gift box containing Agarbatti, Panchakavya Cup Sambrani, Dhristi Camphor, Herbal Kumkum, and Vibhoothi. Perfect for festivals and housewarming.',
    image: '/images/combos_category.png',
    details: ['5 Items Inside', 'Premium Gift Box', 'Festival Ready', 'Free Gift Wrap'],
    weight: 'Combo Pack'
  },
  { 
    name: 'Agarbatti Sampler Gift Pack',
    category: 'Gifting',
    catId: 'gift-packs',
    tagline: '6 Fragrance Discovery Set',
    price: 399,
    originalPrice: 550,
    badge: 'Sampler',
    rating: 4.8,
    reviews: 167,
    bg: '#f3faf0',
    icon: 'Gift',
    desc: 'Discover all 6 Panchakavya Herbal Vastu Agarbathi fragrances in one gift pack — Jungle of Woods, Giggling of Herbs, Little Lavender, Absolute Sandal, Orange, and Mosquito Repellent.',
    image: '/images/combos_category.png',
    details: ['6 Fragrances', 'Mini Packs', 'Charcoal Free', 'Premium Box'],
    weight: '6 × 25g Packs'
  }
];

async function seedDB() {
  try {
    await mongoose.connect(process.env.MONGODB_URI);
    console.log('✅ Connected to MongoDB for seeding...');

    // Clear existing products
    await Product.deleteMany({});
    console.log('🗑️  Cleared old products');

    // Insert new products
    await Product.insertMany(products);
    console.log(`✅ Successfully seeded ${products.length} products!`);

    mongoose.connection.close();
    console.log('👋 Seeding complete, connection closed.');
  } catch (err) {
    console.error('❌ Seeding error:', err);
    process.exit(1);
  }
}

seedDB();
